micronaut:
  server:
    port: ${PORT:8080}
  security:
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_SECRET}

datasources:
  default:
    url: ${DATABASE_URL}
    driverClassName: org.postgresql.Driver

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: false

sql:
  init:
    enabled: false

javamail:
  password: ${MAIL_PASSWORD}

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS}
    allowed-origins-regex: ${APP_CORS_ALLOWED_ORIGINS_REGEX}
  qrcode:
    basepath: ${APP_QRCODE_BASEPATH:qrcodes/}
    baseurl: ${APP_QRCODE_BASEURL:https://seu-backend.onrender.com/api/qrcodes/}

