spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  mail:
    password: ${MAIL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  sql:
    init:
      mode: never
  h2:
    console:
      enabled: false

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS}
  qrcode:
    basepath: ${APP_QRCODE_BASEPATH:qrcodes/}
    baseurl: ${APP_QRCODE_BASEURL:https://seu-backend.onrender.com/api/qrcodes/}

security:
  jwt:
    secret: ${JWT_SECRET}

server:
  port: ${PORT:8080}
